Update to VRCFT 5.2.3.0 & Update to PICO Connect 10.1
regzo2/PicoStreamingAssistantFTUDP pull request #25
Opened 2024-05-17 17:15 UTC by lonelyicer

2024-05-17 19:42 UTC, rogermiranda1000 requested changes
The tests related with reading the old file fails:

![image](https://github.com/regzo2/PicoStreamingAssistantFTUDP/assets/30045337/8ff70772-0d22-46d0-9a21-0eceb9ec27ed)

Please, always consider when updating something, to keep it compatible with older versions. You can't assume all users will always use the latest.

If I were you, I'd try to parse only the file that we need (faceTrackingTransferProtocol), and ignore everything else. That way we'll avoid problems in the future, while keeping compatibility. Thanks.

2024-05-17 19:45 UTC, rogermiranda1000 commented on PicoStreamingAssistantFTUDP.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "VRCFaceTracking.SDK", "..\VRCFaceTracking\VRCFaceTracking.SDK\VRCFaceTracking.SDK.csproj", "{9CE3DF22-4559-4788-9680-FDF924D44D4E}"
I don't recommend adding unrelated projects to the project .sln

2024-05-17 20:01 UTC, lonelyicer commented
> If I were you, I'd try to parse only the file that we need (faceTrackingTransferProtocol), and ignore everything else. That way we'll avoid problems in the future, while keeping compatibility. Thanks.

I didn't think it through very well, sorry, I'll try to fix that part

2024-05-17 20:28 UTC, rogermiranda1000 commented
@lonelyicer I've pushed https://github.com/regzo2/PicoStreamingAssistantFTUDP/pull/27 that is simpler, and provides backwards compatibility.

2024-05-18 15:43 UTC, rogermiranda1000 commented
I think the other alternative https://github.com/regzo2/PicoStreamingAssistantFTUDP/pull/27 is better, and also changes less files (like the .sln project files)

2024-05-18 15:43 UTC, closed without merging